### PR TITLE
Issue 144 replace console logs with using the message component

### LINKED ISSUE #144: Replace console logs with using the message component
Once #139 is done, go through the code looking for places where we console.log an error message (or maybe a success message) and instead use the message component to create a nice looking visible display of the error to the user. The error handling on the leaderboard page should also be changed to use the message component.

If you don't know how to describe the error that is happening, just have the component show "An unexpected error occurred".

### PR DESCRIPTION
**Pull request by aradavi63**
## Change Summary
Change error message to use generic message component in:
- user.ts for login and registration modal
- PreferenceView.vue
- LeaderboardView.vue
I (Adam) saw a discrepancy between login and registration modal and fixed it

### Change Form
**Fill this up (NA if not available). If a certain criteria is not met, can you please give a reason.**

- [ ] The pull request title has an issue number
- [ ] The change works by "Smoke testing" or quick testing
- [ ] The change has tests
- [ ] The change has documentation

## Other Information
Might need to find more places for an error message

# Related issue

- Resolve #144

### CODE REVIEW

File: client/src/stores/user.ts [hunk 1]
```diff
@@ -39,11 +40,13 @@ export const useUserStore = defineStore('user', () => {
       return true
     } catch (error) {
       if (isAxiosError(error)) {
-        console.error('Login failed:', error.response?.data || error)
-        alert(`Error: ${error.response?.data?.message || 'Login failed.'}`)
+        messageStore.showMessage(
```
Comment (HuxleyBerry) [inline client/src/stores/user.ts]: Don't display ``error.response?.data?.message`` in the message component. See my comment here: https://github.com/codersforcauses/bluecrew/issues/144#issuecomment-2630456417

File: client/src/views/LeaderboardView.vue [hunk 2]
```diff
@@ -62,7 +63,8 @@ const fetchLeaderboard = async () => {
       leaderboardData.value = data.map((entry) => transformEntry(entry))
     }
   } catch (err) {
-    error.value = err instanceof Error ? err.message : 'Failed to fetch leaderboard data'
+    const errorMessage = err instanceof Error ? err.message : 'Failed to fetch leaderboard data'
```
Comment (HuxleyBerry) [inline client/src/views/LeaderboardView.vue]: Just make this error message always say 'Failed to fetch leaderboard data'

File: client/src/stores/user.ts [hunk 3]
```diff
@@ -62,15 +65,13 @@ export const useUserStore = defineStore('user', () => {
     try {
       // API call to register using axios server instance
       const response = await server.post('/register/', body)
-      console.log('Registration successful:', response.data)
+      messageStore.showMessage('Registration successful', response.data, 'success')
```
Comment (HuxleyBerry) [inline client/src/stores/user.ts]: Don't show ``response.data`` here, it's not a string! The result is this:

image

File: client/src/stores/user.ts [hunk 4]
```diff
@@ -62,15 +65,13 @@ export const useUserStore = defineStore('user', () => {
...
       return true
     } catch (error) {
       if (isAxiosError(error)) {
-        console.error('Registration failed:', error.response?.data || error)
-        alert(`Error: ${error.response?.data?.message || 'Registration failed.'}`)
+        messageStore.showMessage('Registration failed.', error.response?.data || error, 'error')
```
Comment (HuxleyBerry) [inline client/src/stores/user.ts]: Same thing: don't show ``error.response?.data``. Showing the information contained within that error should be done using the error props of the ``v-text-field``s in the register modal, which will be done in a different issue.

**Review by HuxleyBerry — CHANGES_REQUESTED** [review]

File: client/src/stores/user.ts (hunk 1 above)
Comment (survivzhang) [reply client/src/stores/user.ts]: Screenshot 2025-02-05 at 2 17 04 AM
Done

File: client/src/stores/user.ts (hunk 3 above)
Comment (survivzhang) [reply client/src/stores/user.ts]: Screenshot 2025-02-05 at 2 20 18 AM
User.ts Done

File: client/src/stores/user.ts (hunk 4 above)
Comment (survivzhang) [reply client/src/stores/user.ts]: Done with above

File: client/src/views/LeaderboardView.vue (hunk 2 above)
Comment (survivzhang) [reply client/src/views/LeaderboardView.vue]: Screenshot 2025-02-05 at 2 23 42 AM
Fix as a stand value

File: client/src/views/LeaderboardView.vue [hunk 5]
```diff
@@ -61,8 +62,13 @@ const fetchLeaderboard = async () => {
       // Not logged in, show all entries
       leaderboardData.value = data.map((entry) => transformEntry(entry))
     }
-  } catch (err) {
-    error.value = err instanceof Error ? err.message : 'Failed to fetch leaderboard data'
+  } catch (err: unknown) {
+    // Use unknown type and type guard to ensure type safety
+    if (err instanceof Error) {
+      messageStore.showMessage('Error', `Failed to fetch leaderboard data: ${err.message}`, 'error')
```
Comment (HuxleyBerry) [inline client/src/views/LeaderboardView.vue]: I'd suggest getting rid of ``err.message``, and just show the same error no matter what. Technical users can still use their browser's devtools to see what the error was if they want.

**Review by HuxleyBerry — APPROVED** [review]
